# Generated by Django 4.2.1 on 2023-05-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_id', models.TextField()),
                ('order_date', models.DateField()),
                ('ship_date', models.DateField()),
                ('ship_mode', models.TextField()),
                ('customer_id', models.TextField()),
                ('customer_name', models.TextField()),
                ('segment', models.TextField()),
                ('country', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('postal_code', models.TextField()),
                ('region', models.TextField()),
                ('product_id', models.TextField()),
                ('category', models.TextField()),
                ('sub_category', models.TextField()),
                ('product_name', models.TextField()),
                ('sales', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
